### PR TITLE
add --force-in-progress flag to let migrate steamroll things stuck in progress

### PR DESCRIPTION
**Pull request by silvia-anderson**
I'm super not sure how to test this, but apparently it can semi consistently happen from helm getting stuck and @bmperrea gets it a lot

### CODE REVIEW

**Review by JohnAmican — APPROVED** [review]
Does this handle when a row in the migrations table gets stuck in IN_PROGRESS? If not, can we document how to manually fix it if that happens?

**Comment by bmperrea** [comment]
Is this different from setting `ignore_concurrent` in the validator like from here https://github.com/Cobliteam/cassandra-migrate/blob/b499f780e946907365fac25ff7a0947dab9a538f/cassandra_migrate/migrator.py#L287

**Comment by silvia-anderson** [comment]
it is for the validator but there's other stuff that had to be changed

they really really don't want you to do this

**Comment by silvia-anderson** [comment]
er, it's the same for the validator, i mean

but then i also had to write cleanup_stuck_in_progress to get rid of those ones

**Pull request merged**
